USE ProjetoDB;

CREATE TABLE SETOR(
	ID_SETOR INT (11) NOT NULL auto_increment,
	NOME_SETOR VARCHAR (100) NOT NULL,
	DESCRICAO VARCHAR (255),
	PRIMARY KEY (ID_SETOR)
);

CREATE TABLE FUNCIONARIO (
	ID_FUNCIONARIO INT(11) NOT NULL auto_increment,
	NOME VARCHAR (150) NOT NULL,
	CPF VARCHAR (14) NOT NULL UNIQUE,
	CARGO VARCHAR (100) NOT NULL,
	EMAIL VARCHAR (150) NOT NULL,
	TELEFONE VARCHAR (20),
	ID_SETOR INT (11) NOT NULL,
	PRIMARY KEY (ID_FUNCIONARIO),
	FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID_SETOR)
	ON DELETE RESTRICT ON UPDATE CASCADE
);