USE ProjetoDB;

CREATE TABLE setor (

    id_setor INT(11) NOT NULL AUTO_INCREMENT,
    nome_setor ENUM('RH','Financeiro','Comercial','TI','Marketing','Operacoes') NOT NULL,
    DESCRICAO VARCHAR(255) NULL,
    PRIMARY KEY (id_setor)
);
 

CREATE TABLE FUNCIONARIO (
	ID_FUNCIONARIO INT(11) NOT NULL auto_increment,
	NOME VARCHAR (150) NOT NULL,
	CPF VARCHAR (14) NOT NULL UNIQUE,
	CARGO VARCHAR (100) NOT NULL,
	EMAIL VARCHAR (150) NOT NULL UNIQUE,
	TELEFONE VARCHAR (20),
	ID_SETOR INT (11) NOT NULL,
	PRIMARY KEY (ID_FUNCIONARIO),
	FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID_SETOR)
	ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE NOTEBOOK(
    ID_NOTEBOOK INT AUTO_INCREMENT,
    PATRIMONIO VARCHAR(50) NOT NULL UNIQUE,
    MARCA VARCHAR(50) NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    NUMERO_SERIE VARCHAR(50) NOT NULL UNIQUE,
    PROCESSADOR VARCHAR(50) NOT NULL,
    MEMORIA_RAM VARCHAR(20) NOT NULL,
    ARMAZENAMENTO VARCHAR(20) NOT NULL,
    DATA_AQUISICAO DATE NOT NULL,
    STATUS ENUM('disponivel','indisponivel') NOT NULL DEFAULT 'disponivel',
    ID_FUNCIONARIO INT NULL,
    PRIMARY KEY (ID_NOTEBOOK),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
    ON DELETE SET NULL ON UPDATE CASCADE
);
